=== Krutarth1997/Motivation/files/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "comments": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "version": {
            "type": "number"
        },
        "fps": {
            "type": "number"
        },
        "time_step": {
            "type": "number"
        },
        "simulation_time": {
            "type": "number"
        },
        "accessible_areas": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "vertices": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            },
                            "minItems": 2,
                            "maxItems": 2
                        }
                    }
                },
                "required": ["id", "vertices"]
            }
        },
        "destinations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "vertices": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            },
                            "minItems": 2,
                            "maxItems": 2
                        }
                    }
                },
                "required": ["id", "vertices"]
            }
        },
        "velocity_model_parameter_profiles": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "time_gap": {
                        "type": "number"
                    },
                    "tau": {
                        "type": "number"
                    },
                    "v0": {
                        "type": "number"
                    },
                    "radius": {
                        "type": "number"
                    }
                },
                "required": ["id", "time_gap", "tau", "v0", "radius"]
            }
        },
        "way_points": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "coordinates": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "minItems": 2,
                        "maxItems": 2
                    },
                    "distance": {
                        "type": "number"
                    }
                },
                "required": ["coordinates", "distance"]
            }
        },
        "distribution_polygons": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "vertices": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            },
                            "minItems": 2,
                            "maxItems": 2
                        }
                    }
                },
                "required": ["id", "vertices"]
            }
        }
    },
    "required": ["version", "fps", "time_step", "simulation_time", "accessible_areas", "destinations", "velocity_model_parameter_profiles", "way_points", "distribution_polygons"]
}

=== Krutarth1997/Motivation/files/bottleneck2.json
{
    "comments": [
        "This file includes all important information",
        "to start a jpscore simulation"
    ],
    "version": 0.1,  
    "fps": 10,
    "time_step": 0.01,
    "simulation_time": 100,
    "accessible_areas": [
        {
        "id": 1,
        "vertices": [
            [50, 100],
            [60, 100],
            [60, 104],
            [50, 104]
        ]
    },
        {
        "id": 2,
        "vertices": [
            [60, 101.4],
            [62, 101.4],
            [62, 102.6],
            [60, 102.6]
        ]
    },
        {
        "id": 3,
        "vertices": [
            [62, 100],
            [65, 100],
            [65, 104],
            [62, 104]
        ]
    }
    ],
    "destinations": [
        {
        "id": 2,
        "vertices": [
            [60, 102.6],
            [60, 101.4]
        ]
    },
        {
        "id": 3,
        "vertices": [
            [62, 101.4],
            [62, 102.6]
        ]
    }
    ],
    "velocity_model_parameter_profiles": [
        {
        "id": 1,
        "time_gap":1,
        "tau": 0.5,
        "v0":1.0,
        "radius":0.15
    },
        {
        "id": 2,
        "time_gap":1,
        "tau": 0.5,
        "v0":0.1,
        "radius":0.2      
    }
    ],
    "way_points": [
        {
        "coordinates": [61, 102],
        "distance": 1
    },
        {
        "coordinates": [64.75, 102],
        "distance": 0.25
    }
    ],
    "distribution_polygons": [
        {
        "id": 1,
        "vertices": [
            [50, 100],
            [53, 100],
            [53, 104],
            [50, 104]
        ]
    },
        {
        "id": 2,
        "vertices": [
            [57, 100],
            [60, 100],
            [60, 104],
            [57, 104]
        ]
    }
    ]
}
